version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - HOST_NAME=host.docker.internal
      - GATEWAY_NAME=gateway.docker.internal
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'